# Generated by Django 3.0.4 on 2020-03-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='JWT'),
        ),
    ]
