version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: django_boilerplate

  memcached:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64

  web:
    build: .
    image: zerossb/django_boilerplate.server:alpine
    command: sh /code/scripts/start.sh
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
